### PR TITLE
Version 2 reorganization - first draft

### PR DESCRIPTION
**Pull request by DougManuel**
See the [ERD](https://lucid.app/lucidchart/b2f907a1-e076-4de7-a294-da407ce1db8f/edit?shared=true&page=0_0#) and [measure.md](https://github.com/Big-Life-Lab/ODM/blob/VOC-variables/site/measure.md) for a summary of changes.

This PR includes only an overview of the proposed additions to the dictionary and tables to allow more specific information about variants and mutations. Subsequent PRs will update the details of the dictionary and the tables, after the overall dictionary changes are approved. 

Changes include the provision for:
- use beyond SARS-CoV-2. See `domainID`. The ODM will be able to more robustly include other biologics, chemicals, drugs and health risks.
- environmental testing beyond wastewater. See `specimenID`.
- reporting variants, mutations, gene, and sequencing. See `measureGroupID` and `measureClassID`.
- refactor aggregations and units into separate reference tables.

### CODE REVIEW

**Comment by yulric** [comment]
@DougManuel @jeandavidt Sorry, I'm a little confused. Where in all these tables would one actually record the value obtained from a test? I believe it was in the `value` column of the now deleted `WWMeasure` table.

**Comment by jeandavidt** [comment]
In the proposed schema, the value would be recorded in the `value` column of the `value` table.

However, I'm not too crazy about the fact that any value can be stored in this field, regardless of type. 

@DougManuel  @yulric 
Should we have a `value_int` column, a `value_float` column, a `value_bool` column, and a `value_blob` column?
If so, the `Unit` table would be in charge of defining the data type of the recorded value.

**Comment by yulric** [comment]
> In the proposed schema, the value would be recorded in the `value` column of the `value` table.
> 
> However, I'm not too crazy about the fact that any value can be stored in this field, regardless of type.
> 
> @DougManuel @yulric
> Should we have a `value_int` column, a `value_float` column, a `value_bool` column, and a `value_blob` column?
> If so, the `Unit` table would be in charge of defining the data type of the recorded value.

Thanks, that clears that up.

I'm good with anything going into the `value` column and then validating it with the referenced unit in the `unitID` column.

**Comment by yulric** [comment]
@DougManuel @jeandavidt I think it would be nice to see the following in a change log,

1. What entities (tables/columns) were removed and the reason. If they were replaced by another entity, it should be mentioned.
2. What new entities were added

**Comment by DougManuel** [comment]
> @DougManuel @jeandavidt I think it would be nice to see the following in a change log,
> 
> 1. What entities (tables/columns) were removed and the reason. If they were replaced by another entity, it should be mentioned.
> 2. What new entities were added

Good idea. @jeandavidt why don't you or I take that on. We can just start adding to the existing changelog.

**Comment by jeandavidt** [comment]
@DougManuel  Ok! I'll do a first pass, and you can look it over after :)

**Comment by DougManuel** [comment]
@jeandavidt 

1) Should we add the schema for `Value.csv` as a `dictionary_table`?
2) The allowable type for `value` is challenging and I can't find a perfect solution. 
- In an earlier draft for VOC variables, I had suggested that we allow float numbers with integers used for boleen and categories. i.e. True = 1, False =0. If we go this way, we could add the category values to Unit.csv. This approach is probably the most common approach. I don't think we have free text anywhere. We did consider having variant type as a value, but we dismissed consideration for that approach in favour of our current proposal with `measureType`.
- Allowing any time is possible but this option will generate considerable challenges and headaches coersing types. I don't think we should use this approach.
- Having different value variables is an option, but I haven't seen the approach used. i.e. value_int, value_booleen, value_float. This approach would add variables to the value table, but there would be a finite and management number of value_type variables. It is akward in that there will be a lot of missing or NA values.

**Comment by jeandavidt** [comment]
@DougManuel 

1. To me, the `Value` table is a good example of a data table, as it 
    * contains the actual reported data 
    * Its contents contrains data that is specific to a user (conversely, the dictionary tables contain definitions that could be referenced by anyone).
2. I agree that having multiple columns for values could be cumbersome, but
    * There exists a finite number of possible datatypes for databases, so the number of value columns wouldn't grow past a certain point.
    * It only is cumbersome to the user if they actually *look* at the table. And since most, if not all, users go through a layer of mapping to commit data, and having type-safe data is convenient when validating and extracting data, I feel like the advantages of multiple value columns outweigh the disadvantages at both the read and the write stages.

**Comment by GauriSaran** [comment]
I feel the same as @jeandavidt. The validation part will become much easier if different datatypes are separated in different columns.

**Comment by DougManuel** [comment]
>To me, the Value table is a good example of a data table, as it
contains the actual reported data
It contains data that is specific to a user (conversely, the dictionary tables contain definitions that could be referenced by anyone).

@jeandavidt I'm not sure if I don't follow or don't agree. 

1) It is difficult to follow the dictionary and schema if we have a value table in the ERD but no reference to the table.
2) Describing what variables are in Values.csv is important to ensure we have consistent expectations and valid data in the Valid.csv data table.
3) We need to describe the 'value' variable(s) somewhere. We also need validation rules for 'value' data.

**Comment by DougManuel** [comment]
>I agree that having multiple columns for values could be cumbersome, but
There exists a finite number of possible datatypes for databases, so the number of value columns wouldn't grow past a certain point.
It only is cumbersome to the user if they actually look at the table. And since most, if not all, users go through a layer of mapping to commit data, and having type-safe data is convenient when validating and extracting data, I feel like the advantages of multiple value columns outweigh the disadvantages at both the read and the write stages.

I am of different minds - clearly, there is no perfect solution. Why don't we have the different `value_type` variables, but this is one area where we should be open to feedback during the review. 

I lean towards allowing only float (no text or characters) because this is the most widely used approach -- at least that I am aware of. But I am OK going with the majority (@jeandavidt and @GauriSaran), at least for now. ;) 

Regardless, we will want to be explicit about allowable values in Scale or Units.csv

**Comment by jeandavidt** [comment]
> > To me, the Value table is a good example of a data table, as it
> > contains the actual reported data
> > It contains data that is specific to a user (conversely, the dictionary tables contain definitions that could be referenced by anyone).
> 
> @jeandavidt I'm not sure if I don't follow or don't agree.
> 
> 1. It is difficult to follow the dictionary and schema if we have a value table in the ERD but no reference to the table.
> 2. Describing what variables are in Values.csv is important to ensure we have consistent expectations and valid data in the Valid.csv data table.
> 3. We need to describe the 'value' variable(s) somewhere. We also need validation rules for 'value' data.

No no, I agree with you. I think we are misunsderstanding each other.

The Value table fields have to be defined, that's for sure. That's being done in the `Variables.csv` file just like always.

But I'm making a distinction in my head between "dictionary tables" that define measures/units/aggregations/etc (these contain rows that could be shipped with the ODM), and "data tables" that must be filled in by users using their own WBE data for it to make sense (the ODM dev team can't report TSS values in a sample taken in some plant in some village, but it *can* pre-define what the `TSS` row of the measure table is, along with its units, its allowable aggregations, etc.). 

I am not against putting in "dummy" data in data tables though - I just think it serves another purpose (showing users how to fill a table) than the data we put in the "dictionary tables" (enforcing a standard dictionary of terms)

**Comment by DougManuel** [comment]
@jeandavidt I _think_ we are on the same page. I really like having both the data_tables and dictionary_tables, but I think we need both. The data_table is example data. We could use examples from uOttawa or uLaval lab for some of the data_table examples. We could talk off-line to make sure we are on the same page.

**Comment by Bahamyirou** [comment]
@jeandavidt  Any reason why **AssayHasInstrument** and **Assay** are split ? Isn't simple to merge both into one table. ?

**Comment by jeandavidt** [comment]
> @jeandavidt Any reason why **AssayHasInstrument** and **Assay** are split ? Isn't simple to merge both into one table. ?

Having it in a different table makes it possible to model many-to-many relationships (i.e., one assay can use multiple instruments, and one instrument can be in multiple assays). If we were to model the relationship directly in the assay table, it would take the form of a field with a foreign key to instrumentID, which could only hold one instrument ID per assay

**Comment by Bahamyirou** [comment]
> > @jeandavidt Any reason why **AssayHasInstrument** and **Assay** are split ? Isn't simple to merge both into one table. ?
> 
> Having it in a different table makes it possible to model many-to-many relationships (i.e., one assay can use multiple instruments, and one instrument can be in multiple assays). If we were to model the relationship directly in the assay table, it would take the form of a field with a foreign key to instrumentID, which could only hold one instrument ID per assay

**Comment by jeandavidt** [comment]
I finished filling in the dictionary tables with what was originally in VariableCategory.

While I did that I saw that I had to repeat the same things a lot of times in the `UnitHasAggregation` table - that's because all units that scale linearly have the same aggregations, so basically, only Ct (which is logarthimic) was different from the others. 
So I propose we add a table with the different ways values can aggregate (for now, linear and logarithmic). Tentative name would be  `AggregationScale`. Then, we could replace `UnitHasAggregation` by `AggregationHasAggregationScale`. This way, if we add a linear aggregation (say, percentile), it becomes available to all measurements that can handle it automatically, and so on.

**Comment by jeandavidt** [comment]
I'm also questioning whether the `specimen` table should be linked like this. Right now, a measure that can be done identically at the sample-level (using lab bench methods) or at the site-level (using an online probe) like ammonium nitrogen would have to be entered several times, with slightly different short names, primary id, etc.

Maybe it would be best to have a many-to-many relationship there? That would need we need to add a `MeasureHasSpecimen` table.

Any downsides to making that change that you can see?

**Comment by DougManuel** [comment]
> Tentative name would be AggregationScale. Then, we could replace UnitHasAggregation by AggregationHasAggregationScale. 

Your suggestion sounds a lot like LOINC scale attribute. I suggest we explore or propose within the ODM.

**Review by DougManuel — COMMENTED** [review]
We've made considerable changes to the organization of version 2 based on comments and discussions in this PR and working group meetings.

I will close this PR without committing to preserve the discussion. We will make a new PR with the next V2 draft.

**Pull request closed without merging**
