### PR TITLE
V2 RC2

### PR DESCRIPTION
**Pull request by mathew-thomson**
Updated dictionary tables for review that are consistent and drafted for release candidate 2. Additional edits of these tables and the folder structure may be required upon review.

### CODE REVIEW

**Comment by DougManuel** [comment]
I suggest that we make the following changes to the table headers.
- `contID` --> `contactID`
- `orgID` --> `organizationID`
- `addID` --> `addressID`
- `instID` --> `instrumentID`

This change would be consistent with how we are naming the other primary keys. We can have somewhat longer names now that we have a shortName for tables.

**Review by il43 — APPROVED** [review]
From a quick review, it looks good!

**Comment by jeandavidt** [comment]
The PR *looks* good, but it's kind of hard to tell if, say, the parts table is consistent just by looking.
Maybe it's time we start building a small test suite?
That way we could automate checking whether:

* any part is duplicated
* every row of the parts table has a part ID
* every part is present in the translations table.
* for every language represented in the translations table, that each part has a translation.

That the SQL builds with:

* SQLite (python3)
* potentially other target databases

We could even have a script that parses the parts table to rebuild the SQL schema and compare that to the Lucid-generated schema and fail if they don't match

Having a list of checks like that would help be a lot more confident that the RC is self-consistent

**Comment by DougManuel** [comment]
I agree with all of @jeandavidt comments. We can eventually use the ODM-validator to perform consistency and validation checks, but we should probably find more manual approaches for now. I create a few pivot tables in the Excel 'summary' tab that I've been using to perform validation and consistency checks as described above. So far so good.

Note also that @sorin identified the cycle issue in the ERD. 

> I found the culprits for the cycles. They were the relationships between:
sets.partID - parts.partID
datasets.funderID - organizations.orgID
datasets.custodyID - organizations.orgID
datasets.funderCont - contacts.contID
datasets.custodyCont - contacts.contID
The relationships were corrected in the tab [ERD V2 RC2+partID]

**Comment by DougManuel** [comment]
partID `parSampleID` is not used.  I renamed `parSampleID` to `parent` and depreciated the part in version 2. 

We replaced the concept of sample parents in version 1 with sample relationships in version 2. In version 1, we had a variable in the sample table `parent`.

I added a note that we updated the sample relationship approach.

**Comment by DougManuel** [comment]
Do we want to store polygon files in version 2? In version 1, we stored these files `sewerNetworkFileBLOB` and we had files that referenced the polygon file. 

In version 2, we reference the polygon file but we do not include it.

### What is in version 1.1.
**Site**
- sewerNetworkFileLink:(Sewer network file link): [string] Link to a file that has any detailed information about the sewer network associated with the site (any format).
- sewerNetworkFileBLOB:(Sewer network file blob): [blob] A file blob that has any detailed information about the sewer network associated with the site (any format).

**Polygon**
- wkt:(Wkt): [string] well known text of the polygon
- file:(File): [blob] File containing the geometry of the polygon, blob format.
- link:(Link): [string] Link to an external reference that describes the geometry of the polygon.

**Comment by jeandavidt** [comment]
I think retaining the ability to store sewer network files (and potentially other files) would be good, but I'm not sure how to do this with the new structure.

Currently, the "Value" field of measureReport is a "varchar," so it can act as a catch-all for every other type. But files are binaries, so that wouldn't work in a varchar field, would it? 

Maybe we could have another field in measureReport, "valueBlob," where binary data could be entered. 
Then, when measure reports report files, the "value" field could be used to store the file name (and extension), and valueBlob could be used for the binary data itself.

**Comment by DougManuel** [comment]
For the measures table:

`measureLic` was added to the ERD and parts list. Note that this addition was initially `measLicence` but I updated the name to be consistent with other `measure` parts.
`refLink` was added to the ERD and parts list.

@sorinsion were you going to write a description for these fields, or has that been done by @mathew-thomson.

Note that there is a sharing schema that has been drafted that has a more extensive implementation than `measureLic` (measure license). It is planned to add the sharing and validation schema to the ERD and SQL definitions to highlight that these are available -- even thou they are not directly linked to other tables with keys. 

We need to sort out how to have both the `measureLic` in the measure table and also in the sharing schema. If I remember, we were going to use `measureLic` as a quick approach for measures that can be publicly shared. 

The sharing schema would be a more nuanced approach that allows any field within ODM data to have different layers of sharing. For example, a measure such as reporter email may be shared with a specific organization but not publicly. The sharing schema allows for these different sharing and access permissions.

**Pull request merged**
